### ISSUE TITLE
EPEERINVALID Error while doing npm install

### ISSUE THREAD

**Issue by manishsingh10895** [ajtowf/ng2_play#13]
I'm working on a new installation of Ubuntu 14.04, node version 4.5.0, npm version 2.15.9.

I cloned this project and I'm Getting this error

`npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/home/manish/.nvm/versions/node/v4.5.0/bin/node" "/home/manish/.nvm/versions/node/v4.5.0/bin/npm" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package @angular/core@2.0.0-rc.5 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/common@2.0.0-rc.5 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/compiler@2.0.0-rc.5 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/forms@0.3.0 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/http@2.0.0-rc.5 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-browser@2.0.0-rc.5 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/platform-browser-dynamic@2.0.0-rc.5 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular/router@3.0.0-rc.1 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer @angular2-material/core@2.0.0-alpha.7 wants @angular/core@^2.0.0-rc.5
npm ERR! peerinvalid Peer angular2-jwt@0.1.21 wants @angular/core@^2.0.0-rc.6

npm ERR! Please include the following file with any support request:
npm ERR!     /home/manish/Documents/Angular/NgPlay/npm-debug.log
`

Is this a problem with npm version, or something else ?

**Comment by ajtowf** [comment]
Update npm to v3+
