### ISSUE TITLE
Does this application compile with angular cli webpack?

### ISSUE THREAD

**Issue by shootdaj** [ajtowf/ng2_play#14]
I downloaded this app yesterday and tried to build, but it kept having issues with angular cli. Kept saying that this app was generated using an older version of angular cli.. And it directed me to an upgrade page. You can recreate it by removing your existing installation of angular cli, npm cache clean, then reinstall latest version of angular cli, then try rebuilding. Can you please verify that it doesn't work with the latest (webpack) version of the cli? Thanks.

**Comment by shootdaj** [comment]
Here's the error I'm getting when I run ng serve:

> It seems like you're using a project generated using an old version of the Angular CLI.
> The latest CLI now uses webpack and includes a lot of improvements, include a simpler
> workflow, a faster build and smaller bundles.
> 
> To get more info, including a step-by-step guide to upgrade the CLI, follow this link:
> https://github.com/angular/angular-cli/wiki/Upgrading-from-Beta.10-to-Beta.12

**Comment by ajtowf** [comment]
I'll update this repo to angular 2.0.1 and angular-cli beta.15 that uses webpack soon.

**Comment by shootdaj** [comment]
Thanks
