### ISSUE TITLE
Missing package.json

### ISSUE THREAD

**Issue by screenm0nkey** [ajtowf/ng2_play#2]

**Comment by ajtowf** [comment]
Well we don't really have any node deps so it doesn't make sense to have one, yet. 
I think I'll create a workflow using gulp in the next screencast, then we'll have a packages.json

**Comment by screenm0nkey** [comment]
Sorry Ajden. My bad. I realised that after watching your tut, so I 
removed the comment. Thanks man.

> Ajden Towfeek mailto:notifications@github.com
> 9 September 2015 09:03
> 
> Well we don't really have any node deps so it doesn't make sense to 
> have one, yet.
> I think I'll create a workflow using gulp in the next screencast, then 
> we'll have a packages.json
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/ajtowf/ng2_play/issues/2#issuecomment-138818310.

## 

Sent with Postbox http://www.getpostbox.com
