### ISSUE TITLE
error: Cannot find module 'models' on todo.ts 4,24

### ISSUE THREAD

**Issue by val-samonte** [ajtowf/ng2_play#3]
appreciate your effort for making this tutorial, thanks!
tried to run gulp and i am getting some error when running ts. seems like the todo.ts can't find the 'models' file. i tried changing the path from 'models' to '../models' but still no luck. sorry im kinda noob in angular 2.

**Comment by ajtowf** [comment]
right, so ../ only takes you to the components directory, ../../models does the trick ;-)

**Comment by val-samonte** [comment]
haha, sorry about that. thanks
