### ISSUE TITLE
Breaking changes in angular2/route

### ISSUE THREAD

**Issue by evanplaice** [ajtowf/ng2_play#4]
As of [alpha41](https://github.com/angular/angular/blob/master/CHANGELOG.md#200-alpha41-2015-10-13) `ROUTER_BINDINGS` has been deprecated and replaced with `ROUTER_PROVIDERS`

``` javascript
bootstrap(AppComponent, [
    ROUTER_BINDINGS,
    bind(LocationStrategy).toClass(HashLocationStrategy)
]);
```

Should be...

``` javascript
bootstrap(AppComponent, [
    ROUTER_PROVIDERS,
    bind(LocationStrategy).toClass(HashLocationStrategy)
]);
```

**Comment by ajtowf** [comment]
Sorry for late response, repo is now up to date with beta0 in a1dd63dc29d452fa2a87069664e78cb87a7b85f9
