### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by thinhhuynh** [ajtowf/ng2_play#6]
@ajtowf 

I ran sudo npm install and sudo gulp command successfully
But there are errors in console of browser as below:

Uncaught SyntaxError: Unexpected token )__exec @ system.src.js:1436esmRegEx @ system.src.js:3284(anonymous function) @ system.src.js:3552loader @ system.src.js:3800(anonymous function) @ system.src.js:4147negation @ system.src.js:4383(anonymous function) @ system.src.js:346Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451(anonymous function) @ angular2-polyfills.js:123Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262

Uncaught SyntaxError: Unexpected token )                                                          angular2-polyfills.js:1243 
    Evaluating http://localhost:3000/app/boot.js
    Error loading http://localhost:3000/app/boot.jsZone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$$internal$$tryCatch @ angular2-polyfills.js:468lib$es6$promise$$internal$$invokeCallback @ angular2-polyfills.js:480lib$es6$promise$$internal$$publish @ angular2-polyfills.js:451lib$es6$promise$$internal$$publishRejection @ angular2-polyfills.js:401(anonymous function) @ angular2-polyfills.js:123Zone.run @ angular2-polyfills.js:1243zoneBoundFn @ angular2-polyfills.js:1220lib$es6$promise$asap$$flush @ angular2-polyfills.js:262

**Comment by ajtowf** [comment]
Hi sorry for late response, what browser and version are you using? Just updated the repo to beta 9 do you still have the same problem?

**Comment by thinhhuynh** [comment]
Thanks Ajden, It has great worked for me.

Regards,
Thinh Huynh

On Sun, Mar 13, 2016 at 6:23 PM, Ajden Towfeek notifications@github.com
wrote:

> Hi sorry for late response, what browser and version are you using? Just
> updated the repo to beta 9 do you still have the same problem?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ajtowf/ng2_play/issues/6#issuecomment-195938182.

## 

Thinh Huynh Doan
Software Engineer

**Comment by ajtowf** [comment]
Great, closing issue then.
