### ISSUE TITLE
browserSync error

### ISSUE THREAD

**Issue by aperezl** [ajtowf/ng2_play#9]
browserSync startup sometimes crash watching node_modules folder.

```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: watch node_modules/angular2/es6/dev/src/platform/dom/debug/ng_probe.js ENOSPC
```

I changed in gulpfile.js

```
files: ['index.html', '**/*.js'],
```

to

```
files: ['index.html', 'app/**/*.js'],
```

**Comment by aperezl** [comment]
Other solution in Ubuntu is increase max_user_watches

`echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
`

See: http://stackoverflow.com/a/17437601

**Comment by ajtowf** [comment]
Thx, no reason to watch the node_modules folder though :-)
